"""empty message

Revision ID: 1c5da1f600e9
Revises: 
Create Date: 2019-01-09 18:08:27.827890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5da1f600e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('class_leader', sa.Integer(), nullable=True),
    sa.Column('createdon', sa.String(length=500), nullable=True),
    sa.Column('updatedon', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['class_leader'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('createdon', sa.String(length=500), nullable=True),
    sa.Column('updatedon', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('class')
    # ### end Alembic commands ###
