"""empty message

Revision ID: 2e93f9162016
Revises: ee62ce8ce0aa
Create Date: 2019-01-06 14:08:41.842601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e93f9162016'
down_revision = 'ee62ce8ce0aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'class', 'student', ['class_leader'], ['id'])
    op.create_foreign_key(None, 'student', 'class', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'class', type_='foreignkey')
    # ### end Alembic commands ###
