"""empty message

Revision ID: 30e71b55bbcf
Revises: 
Create Date: 2019-01-10 15:49:43.403125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e71b55bbcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    class_table = op.create_table('class',
    sa.Column('id', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('class_leader', sa.String(length=500), nullable=True),
    sa.Column('createdon', sa.String(length=500), nullable=True),
    sa.Column('updatedon', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['class_leader'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    student_table = op.create_table('student',
    sa.Column('id', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('class_id', sa.String(length=500), nullable=True),
    sa.Column('createdon', sa.String(length=500), nullable=True),
    sa.Column('updatedon', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('class')
    # ### end Alembic commands ###
