"""empty message

Revision ID: 4f273a4a6371
Revises: f5d0c232f24e
Create Date: 2019-01-11 00:47:48.939649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f273a4a6371'
down_revision = 'f5d0c232f24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('class_key_fk', 'class', 'student', ['class_leader'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('student_key_fk', 'student', 'class', ['class_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_key_fk', 'student', type_='foreignkey')
    op.drop_constraint('class_key_fk', 'class', type_='foreignkey')
    # ### end Alembic commands ###
