"""empty message

Revision ID: ee62ce8ce0aa
Revises: 
Create Date: 2019-01-06 13:41:30.470291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee62ce8ce0aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    class_table = op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('class_leader', sa.Integer(), nullable=True),
    sa.Column('createdon', sa.String(length=500), nullable=True),
    sa.Column('updatedon', sa.String(length=500), nullable=True),
    #sa.ForeignKeyConstraint(['class_leader'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )

    op.bulk_insert(class_table,
                   [
                       {'id': 102, 'name': '10th B', 'class_leader': 1, 'createdon': '01/03/19 07:45:54',
                        'updatedon': '01/03/19 07:45:54'},
                       {'id': 103, 'name': '10th C', 'class_leader': 2, 'createdon': '01/03/19 07:45:54',
                        'updatedon': '01/03/19 07:45:54'},
                       {'id': 104, 'name': '10th D', 'class_leader': 3, 'createdon': '01/03/19 07:45:54',
                        'updatedon': '01/03/19 07:45:54'},
                   ]

                   )



    student_table = op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('createdon', sa.String(length=500), nullable=True),
    sa.Column('updatedon', sa.String(length=500), nullable=True),
    #sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(student_table,
                   [
                       {'id': 1, 'name': 'Ratan Boddu', 'class_id': 102, 'createdon':'01/03/19 07:45:54',
                        'updatedon':'01/03/19 07:45:54'},
                       {'id': 2, 'name': 'Sarvesh Deshmukh', 'class_id': 103, 'createdon': '01/03/19 07:45:54',
                        'updatedon': '01/03/19 07:45:54'},
                       {'id': 3, 'name': 'Harsh Parikh', 'class_id': 104, 'createdon': '01/03/19 07:45:54',
                        'updatedon': '01/03/19 07:45:54'},
                   ]

                  )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('class')
    # ### end Alembic commands ###
